DROP TABLE IF EXISTS SOLD_PRODUCT_DETAILS;
CREATE TABLE SOLD_PRODUCT_DETAILS(
	PRODUCT_ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_NAME VARCHAR(50) NOT NULL,
	PRODUCT_PRICE DECIMAL(10,2) NOT NULL,
	PRODUCT_SIZE VARCHAR(50) NOT NULL,
	PRODUCT_SOLD_QUANTITY INT(10) NOT NULL,
	PRODUCT_SOLD_DATE DATE NOT NULL,
	IS_ACTIVE CHAR NOT NULL,
	CREATED_BY INT(10) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_BY INT(10),
	LAST_MODIFIED_DATE TIMESTAMP,
	VERSION INT(10) NOT NULL
);